In [24]:
from google.colab import drive
drive.mount('/gdrive')
%cd /gdrive

ERROR:root:Internal Python error in the inspect module.
Below is the traceback from this internal error.

Mounted at /gdrive
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-24-cd0a7580851e>", line 3, in <module>
    get_ipython().magic('cd /gdrive')
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2160, in magic
    return self.run_line_magic(magic_name, magic_arg_s)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2081, in run_line_magic
    result = fn(*args,**kwargs)
  File "</usr/local/lib/python3.6/dist-packages/decorator.py:decorator-gen-91>", line 2, in cd
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/magic.py", line 188, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/magics/osm.py", line 288, in cd
    oldcwd = py3compat.getcwd()
OSError: [Errno 107] Transport endpoint is not connected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 1823, in showtraceback
    stb = value._render_traceback_()
AttributeError: 'OSError' object has no attribute '_render_traceback_'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 1132, in get_records
    return _fixed_getinnerframes(etb, number_of_lines_of_context, tb_offset)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 313, in wrapped
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/ultratb.py", line 358, in _fixed_getinnerframes
    records = fix_frame_records_filenames(inspect.getinnerframes(etb, context))
  File "/usr/lib/python3.6/inspect.py", line 1490, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/usr/lib/python3.6/inspect.py", line 1448, in getframeinfo
    filename = getsourcefile(frame) or getfile(frame)
  File "/usr/lib/python3.6/inspect.py", line 696, in getsourcefile
    if getattr(getmodule(object, filename), '__loader__', None) is not None:
  File "/usr/lib/python3.6/inspect.py", line 725, in getmodule
    file = getabsfile(object, _filename)
  File "/usr/lib/python3.6/inspect.py", line 709, in getabsfile
    return os.path.normcase(os.path.abspath(_filename))
  File "/usr/lib/python3.6/posixpath.py", line 383, in abspath
    cwd = os.getcwd()
OSError: [Errno 107] Transport endpoint is not connected

OSError: ignored

In [128]:
import pandas as pd
import os

In [129]:
files=[file for dirpath,directory,file in os.walk('./all_csv/')][0]
# files=[file for dirpath,directory,file in os.walk(r'/gdrive/My Drive/all_csv/')][0]

In [130]:
match_data=pd.DataFrame(data=None)
odi_scorecard=pd.DataFrame(data=None)
ttwenty_scorecard=pd.DataFrame(data=None)
odi_info=pd.DataFrame(data=None)
ttwenty_info=pd.DataFrame(data=None)

In [131]:
def rename_date_umpire(index_list):
    n=0
    for i in range(index_list.__len__()):
        if str.lower(index_list[i]).strip()=='date':
            index_list[i]+='_'+str(n)
            n+=1
    n=0
    for i in range(index_list.__len__()):
        if str.lower(index_list[i]).strip()=='umpire':
            index_list[i]+='_'+str(n)
            n+=1
    return index_list

In [132]:
def find_game(df_game,df_info):
    if 'series' in df_info.columns:
        if 'odi' in str.lower(df_info.iloc[0]['series']):
            return 'odi'
        if 't20i' in str.lower(df_info.iloc[0]['series']) or 't20' in str.lower(df_info.iloc[0]['series']) or 'indian premier league' in str.lower(df_info.iloc[0]['series']) :
            return 'twenty'
    if max(df_game['balls_bowl'])<=24:
        return 'twenty'
    if 24<max(df_game['balls_bowl'])<=60:
        return 'odi'
    return

In [133]:
def append_file(temp_df,temp_info_df,type_game):
    global odi_scorecard
    global ttwenty_scorecard
    global odi_info
    global ttwenty_info
    if type_game=='odi':
        odi_scorecard=odi_scorecard.append(temp_df,ignore_index=True)
        odi_info=odi_info.append(temp_info_df,ignore_index=True)
    elif type_game=='twenty':
        ttwenty_scorecard=ttwenty_scorecard.append(temp_df,ignore_index=True)
        ttwenty_info=ttwenty_info.append(temp_info_df,ignore_index=True)

In [134]:
def get_extras_type(match_data):
    list_extras=[]
    for index,row in match_data.iterrows():
        ov=str(row['over'])
        if '.' in ov:
            ov=str(row['over']).split('.')
            ball_no=int(ov[1])
            over_no=int(ov[0])
        else:
            continue
        if row['extras']!=0:
            if row['runs']!=0:
                match_data.loc[index,'extras_type']='w'
            list_extras.append(index)
        if ball_no>6:
            if len(list_extras)>0:
                match_data.loc[list_extras.pop(-1),'extras_type']='w'
    for i in list_extras:
        match_data.loc[i,'extras_type']='b'
    return match_data

In [135]:
def prepare_scorecard(match_data):
    match_data=get_extras_type(match_data)
#     print(match_data[match_data['bowler']==	'Mashrafe Mortaza'])
    players=list((match_data['striker'].append(match_data['non-striker']).append(match_data['bowler'])).unique())
    #     to make 22 players if any player has not played
#     for i in range(len(players),22):
#         players.append('p_'+str(i))
#         fow
#     player_stats=['match_id','inning-batting','name','position','over-batsman','score','balls_bat','ones','twos','threes','fours','sixes','out','balls_bowl','maidens','runs_bowled','wickets','bowler_extras','wicket_score','wicket_overs','wicket_no','fow','fow_runs','fow_overs','fow_batsman','fow_bowler']
    player_stats=['match_id','inning-batting','name','position','over-batsman','score','balls_bat','dots','ones','twos','threes','fours','sixes','out','balls_bowl','maidens','runs_bowled','wickets','bowler_extras','wicket_score','wicket_overs','wicket_no','wicket_bowler']
    player_data={key:{key_type:0 for key_type in player_stats} for key in players}
    for p in players:
        player_data[p]['match_id']=match_data.loc[0,'file_no']
        player_data[p]['name']=p
    team_score=0
    balls=0
    pos=1
    inning=False
    w=1
    p_no=1
    w_no=1
    for index, row in match_data.iterrows():
        ov=str(row['over'])
        if '.' in ov:
            ov=ov.split('.')
            ball_no=int(ov[1])
            over_no=int(ov[0])
        else:
            continue
        if over_no>50:
            player_data=[value for key, value in player_data.items()]
            scorecard=pd.DataFrame(data=player_data)
            scorecard=scorecard[player_stats]
            return scorecard
        if ball_no==1 and over_no==0:
            pos=1
            w=1
            team_score=0
            w_no=1
            runs_over=0
            # if row['innings']!=1:
            #     p_no=12
        if row['runs']==1:
            player_data[row['striker']]['ones']+=1
        elif row['runs']==2:
            player_data[row['striker']]['twos']+=1
        elif row['runs']==3:
            player_data[row['striker']]['threes']+=1
        elif row['runs']==4:
            player_data[row['striker']]['fours']+=1
        elif row['runs']==6:
            player_data[row['striker']]['sixes']+=1
        elif row['extras']==0:
            player_data[row['striker']]['dots']+=1

        if player_data[row['striker']]['position']==0:
            player_data[row['striker']]['position']=pos
            player_data[row['striker']]['over-batsman']=row['over']
            pos+=1
        if player_data[row['non-striker']]['position']==0:
            player_data[row['non-striker']]['position']=pos
            player_data[row['non-striker']]['over-batsman']=row['over']
            pos+=1
    # wicket
#         print(row['out-player'])
        if not pd.isna(row['out-player']):
            player_data[row['out-player']]['out']=row['out']
#             fow
#             player_data[players[p_no-1]]['fow']=w
#             player_data[players[p_no-1]]['fow_runs']=team_score
#             player_data[players[p_no-1]]['fow_overs']=row['over']
#             player_data[players[p_no-1]]['fow_batsman']=row['out-player']
#             player_data[players[p_no-1]]['fow_bowler']=row['bowler']
            p_no+=1
            w+=1
            if row['out']!='run out':
                player_data[row['bowler']]['wickets']+=1
            player_data[row['out-player']]['wicket_score']=team_score
            player_data[row['out-player']]['wicket_overs']=row['over']
            player_data[row['out-player']]['wicket_no']=w_no
            player_data[row['out-player']]['wicket_bowler']=row['bowler']
            w_no+=1
        team_score+=row['runs']+row['extras']
        runs_over+=row['runs']
        if row['extras']!=0 and row['extras_type']=='w':
            runs_over+=1
            player_data[row['bowler']]['bowler_extras']+=1
            player_data[row['striker']]['score']+=row['extras']-1
            player_data[row['bowler']]['runs_bowled']+=row['extras']-1
        elif row['extras']!=0:
#             print(row)
            player_data[row['bowler']]['balls_bowl']+=1
            player_data[row['striker']]['balls_bat']+=1
        else:
            player_data[row['striker']]['balls_bat']+=1
            player_data[row['bowler']]['balls_bowl']+=1
            player_data[row['bowler']]['runs_bowled']+=row['runs']
        player_data[row['striker']]['score']+=row['runs']
        if ball_no>=6:
            if ball_no==6 and runs_over==0:
                player_data[row['bowler']]['maidens']+=1
            runs_over=0
        player_data[row['striker']]['inning-batting']=row['innings']
        if row['innings']==1:
            player_data[row['bowler']]['inning-batting']=2
        else:
            player_data[row['bowler']]['inning-batting']=1
#     print(player_data)
    player_data=[value for key, value in player_data.items()]
    scorecard=pd.DataFrame(data=player_data)
    scorecard=scorecard[player_stats]
    return scorecard

In [143]:
i=0
for file in files[:10]:
    print(i,'--',file)
    i+=1
    count=0
    df_index=[]
    df_row=[]
    add=r'./all_csv/'+file
#     add=r'/gdrive/My Drive/all_csv/'+file
    df_index=['file_no']
    file_no=file.split('.')[0]
    df_row=[file_no]
    with open(add) as f:
        new_f=f.readlines()
        for line in new_f:
            if 'version' in line:
                count+=1
            elif 'info' in line:
                count+=1
                line=line.strip().split(',')
                df_index.append(line[1])
                df_row.append(line[2])
            else:
                df_index=rename_date_umpire(df_index)
                df_dic=dict(zip(df_index,df_row),index=[0])
                temp_info_df=pd.DataFrame(df_dic)
#                 df_info=df_info.append(temp_info_df,ignore_index=True)
                # gender=df_info['gender'].iloc[0]
                # gender=str.lower(gender.strip())
                break
    temp_df=pd.read_csv(add,skiprows=count,names=[0,'innings','over','batting-team','striker','non-striker','bowler','runs','extras','out','out-player'])
    temp_df=temp_df.drop([0],axis=1)
    temp_df['file_no']=[file_no]*(temp_df.shape[0])
    temp_sc=prepare_scorecard(temp_df)
    # print(temp_sc)
#     append_file(temp_df,gender,type_game) 
    append_file(temp_sc,temp_info_df,find_game(temp_sc,temp_info_df))

0 -- 1019975.csv
1 -- 682919.csv
2 -- 952191.csv

/home/sb/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py:6692: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  sort=sort)

3 -- 1043961.csv
4 -- 565820.csv
5 -- 335990.csv
6 -- 980959.csv
7 -- 995463.csv
8 -- 1082599.csv
9 -- 1051297.csv

In [144]:
odi_info.columns

Index(['city', 'competition', 'date_0', 'file_no', 'gender', 'index',
       'match_number', 'match_referee', 'player_of_match', 'reserve_umpire',
       'season', 'series', 'team', 'toss_decision', 'toss_winner', 'tv_umpire',
       'umpire_0', 'umpire_1', 'venue', 'winner', 'winner_runs',
       'winner_wickets'],
      dtype='object')

In [145]:
ttwenty_info.columns

Index(['city', 'competition', 'date_0', 'file_no', 'gender', 'index',
       'match_number', 'match_referee', 'neutralvenue', 'player_of_match',
       'reserve_umpire', 'season', 'series', 'team', 'toss_decision',
       'toss_winner', 'tv_umpire', 'umpire_0', 'umpire_1', 'venue', 'winner',
       'winner_runs', 'winner_wickets'],
      dtype='object')

In [146]:
ttwenty_info

,city,competition,date_0,file_no,gender,index,match_number,match_referee,neutralvenue,player_of_match,...,team,toss_decision,toss_winner,tv_umpire,umpire_0,umpire_1,venue,winner,winner_runs,winner_wickets
0,,World T20,2014/03/21,682919,male,0,12,DC Boon,true,SJ Myburgh,...,Netherlands,field,Netherlands,BF Bowden,SJ Davis,IJ Gould,Sylhet Stadium,Netherlands,NaN,6
1,Chennai,NaN,2012/09/11,565820,male,0,2,BC Broad,NaN,BB McCullum,...,New Zealand,field,India,S Asnani,VA Kulkarni,S Ravi,"""MA Chidambaram Stadium",New Zealand,1,NaN
2,Hyderabad,Indian Premier League,2008/04/24,335990,male,0,9,S Venkataraghavan,NaN,YK Pathan,...,Rajasthan Royals,field,Rajasthan Royals,SL Shastri,Asad Rauf,MR Benson,"""Rajiv Gandhi International Stadium",Rajasthan Royals,NaN,3
3,Bangalore,Indian Premier League,2016/05/02,980959,male,0,30,J Srinath,NaN,AD Russell,...,Kolkata Knight Riders,field,Kolkata Knight Riders,K Bharatan,M Erasmus,S Ravi,M Chinnaswamy Stadium,Kolkata Knight Riders,NaN,5
4,Pune,Indian Premier League,2017/04/11,1082599,male,0,9,J Srinath,NaN,SV Samson,...,Delhi Daredevils,field,Rising Pune Supergiant,A Nand Kishore,AY Dandekar,S Ravi,Maharashtra Cricket Association Stadium,Delhi Daredevils,97,NaN

In [147]:
ttwenty_scorecard

,match_id,inning-batting,name,position,over-batsman,score,balls_bat,dots,ones,twos,...,out,balls_bowl,maidens,runs_bowled,wickets,bowler_extras,wicket_score,wicket_overs,wicket_no,wicket_bowler
0,682919,1,WTS Porterfield,1,0.1,47,32,13,9,3,...,bowled,0,0,0,0,0,69,9.1,2,Ahsan Malik
1,682919,1,PR Stirling,2,0.1,7,9,6,1,1,...,caught,12,0,24,0,0,28,3.2,1,T van der Gugten
2,682919,1,EC Joyce,3,3.3,28,25,6,14,2,...,run out,0,0,0,0,0,88,12.3,3,Mudassar Bukhari
3,682919,1,AD Poynter,4,9.2,57,38,12,15,1,...,caught,0,0,0,0,0,189,19.6,4,Ahsan Malik
4,682919,1,KJ O'Brien,5,12.4,42,16,1,8,1,...,0,18,0,29,2,0,0,0.0,0,0
5,682919,2,PW Borren,1,0.1,31,15,4,3,0,...,caught,12,0,18,0,1,91,5.6,1,KJ O'Brien
6,682919,2,SJ Myburgh,2,0.1,63,23,7,3,1,...,caught,0,0,0,0,0,98,6.3,2,GH Dockrell
7,682919,2,W Barresi,3,6.1,40,22,6,10,0,...,0,0,0,0,0,0,0,0.0,0,0
8,682919,2,LV van Beek,4,6.4,1,3,2,1,0,...,caught,6,0,18,0,0,100,7.2,3,KJ O'Brien
9,682919,2,TLW Cooper,5,7.3,45,15,3,3,1,...,caught,6,0,8,0,0,161,11.2,4,TJ Murtagh
10,682919,2,BN Cooper,6,11.3,9,5,2,1,1,...,0,0,0,0,0,0,0,0.0,0,0
11,682919,2,MR Swart,0,0.0,0,0,0,0,0,...,0,24,0,39,0,0,0,0.0,0,0
12,682919,2,T van der Gugten,0,0.0,0,0,0,0,0,...,0,18,0,32,1,0,0,0.0,0,0
13,682919,2,Ahsan Malik,0,0.0,0,0,0,0,0,...,0,24,0,26,2,0,0,0.0,0,0
14,682919,2,Mudassar Bukhari,0,0.0,0,0,0,0,0,...,0,18,0,25,0,1,0,0.0,0,0
15,682919,2,PM Seelaar,0,0.0,0,0,0,0,0,...,0,12,0,15,0,0,0,0.0,0,0
16,682919,1,AR McBrine,0,0.0,0,0,0,0,0,...,0,6,0,24,0,0,0,0.0,0,0
17,682919,1,TJ Murtagh,0,0.0,0,0,0,0,0,...,0,23,0,47,1,0,0,0.0,0,0
18,682919,1,AR Cusack,0,0.0,0,0,0,0,0,...,0,6,0,22,0,0,0,0.0,0,0
19,682919,1,GH Dockrell,0,0.0,0,0,0,0,0,...,0,18,0,43,1,0,0,0.0,0,0
20,565820,1,RJ Nicol,1,0.1,0,4,3,0,0,...,bowled,0,0,0,0,0,2,0.6,1,Z Khan
21,565820,1,MJ Guptill,2,0.1,1,5,4,1,0,...,bowled,0,0,0,0,0,2,1.3,2,IK Pathan
22,565820,1,KS Williamson,4,1.4,28,26,9,12,2,...,caught,0,0,0,0,0,92,12.3,3,IK Pathan
23,565820,1,BB McCullum,3,1.1,91,55,14,25,2,...,bowled,0,0,0,0,0,139,16.4,4,IK Pathan
24,565820,1,LRPL Taylor,5,12.4,25,19,1,15,2,...,0,0,0,0,0,0,0,0.0,0,0
25,565820,1,JEC Franklin,6,16.5,1,2,1,1,0,...,caught,24,0,25,2,1,142,17.2,5,L Balaji
26,565820,1,JDP Oram,7,17.3,18,9,1,4,1,...,0,24,0,27,0,0,0,0.0,0,0
27,565820,2,G Gambhir,1,0.1,3,6,3,3,0,...,caught and bowled,0,0,0,0,0,26,2.6,1,KD Mills
28,565820,2,V Kohli,2,0.1,70,41,9,18,3,...,caught,18,0,27,0,0,120,13.2,3,JEC Franklin
29,565820,2,SK Raina,3,3.1,27,22,8,9,2,...,caught,0,0,0,0,0,86,10.2,2,KD Mills
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
75,980959,2,SA Yadav,7,17.4,10,5,1,2,0,...,0,0,0,0,0,0,0,0.0,0,0
76,980959,1,VR Aaron,8,19.6,0,0,0,0,0,...,0,24,0,30,0,4,0,0.0,0,0
77,980959,2,M Morkel,0,0.0,0,0,0,0,0,...,0,24,0,28,2,0,0,0.0,0,0
78,980959,2,SP Narine,0,0.0,0,0,0,0,0,...,0,24,0,45,0,0,0,0.0,0,0
79,980959,2,UT Yadav,0,0.0,0,0,0,0,0,...,0,24,0,52,1,3,0,0.0,0,0
80,980959,2,PP Chawla,0,0.0,0,0,0,0,0,...,0,24,0,32,2,0,0,0.0,0,0
81,980959,1,S Aravind,0,0.0,0,0,0,0,0,...,0,13,0,13,1,3,0,0.0,0,0
82,980959,1,YS Chahal,0,0.0,0,0,0,0,0,...,0,24,0,25,2,2,0,0.0,0,0
83,980959,1,T Shamsi,0,0.0,0,0,0,0,0,...,0,24,0,51,0,0,0,0.0,0,0
84,1082599,1,AP Tare,1,0.1,0,5,4,0,0,...,caught,0,0,0,0,0,2,1.1,1,DL Chahar
85,1082599,1,SW Billings,2,0.1,24,17,5,8,0,...,bowled,0,0,0,0,0,71,8.1,2,Imran Tahir
86,1082599,1,SV Samson,3,1.2,102,63,16,24,8,...,bowled,0,0,0,0,0,166,18.2,4,A Zampa
87,1082599,1,RR Pant,4,8.2,31,22,5,13,1,...,run out,0,0,0,0,0,124,15.2,3,BA Stokes
88,1082599,1,CJ Anderson,5,15.3,2,4,2,2,0,...,0,6,0,10,0,0,0,0.0,0,0
89,1082599,1,CH Morris,6,18.3,38,9,0,0,2,...,0,12,0,18,1,1,0,0.0,0,0
90,1082599,2,AM Rahane,1,0.1,10,9,1,6,2,...,caught,0,0,0,0,0,24,2.6,1,Z Khan
91,1082599,2,MA Agarwal,2,0.1,20,18,7,6,3,...,caught,0,0,0,0,0,34,4.5,2,Z Khan
92,1082599,2,F du Plessis,3,3.1,8,7,2,4,0,...,caught,0,0,0,0,0,52,6.4,4,S Nadeem
93,1082599,2,RA Tripathi,4,4.6,10,5,2,0,1,...,caught,0,0,0,0,0,49,5.6,3,CH Morris
94,1082599,2,BA Stokes,5,5.7,2,5,3,2,0,...,caught,24,0,41,0,0,54,7.5,5,PJ Cummins
95,1082599,2,MS Dhoni,6,6.5,11,14,8,5,0,...,caught,0,0,0,0,0,79,11.6,6,A Mishra
96,1082599,2,R Bhatia,7,7.6,16,17,6,8,1,...,caught,12,0,21,0,0,94,13.1,7,A Mishra
97,1082599,2,DL Chahar,8,12.1,14,6,2,2,0,...,caught,18,0,33,1,2,100,14.1,8,Z Khan
98,1082599,2,A Zampa,9,13.2,5,7,5,1,0,...,caught,24,0,45,1,0,107,15.3,9,A Mishra
99,1082599,2,AB Dinda,10,14.2,7,7,3,3,0,...,caught,18,0,34,0,2,108,16.1,10,PJ Cummins
100,1082599,2,Imran Tahir,11,15.4,0,2,2,0,0,...,0,24,0,23,1,1,0,0.0,0,0
101,1082599,1,S Nadeem,0,0.0,0,0,0,0,0,...,0,24,0,22,1,1,0,0.0,0,0
102,1082599,1,PJ Cummins,0,0.0,0,0,0,0,0,...,0,19,0,23,2,1,0,0.0,0,0
103,1082599,1,Z Khan,0,0.0,0,0,0,0,0,...,0,18,0,19,3,1,0,0.0,0,0
104,1082599,1,A Mishra,0,0.0,0,0,0,0,0,...,0,18,0,11,3,0,0,0.0,0,0

In [148]:
odi_info

,city,competition,date_0,file_no,gender,index,match_number,match_referee,player_of_match,reserve_umpire,...,team,toss_decision,toss_winner,tv_umpire,umpire_0,umpire_1,venue,winner,winner_runs,winner_wickets
0,Nelson,NaN,2016/12/29,1019975,male,0,2,BC Broad,NT Broom,WR Knights,...,Bangladesh,field,Bangladesh,C Shamshuddin,CM Brown,PR Reiffel,Saxton Oval,New Zealand,67,NaN
1,Nelson,NaN,2016/12/29,1019975,male,0,2,BC Broad,NT Broom,WR Knights,...,Bangladesh,field,Bangladesh,C Shamshuddin,CM Brown,PR Reiffel,Saxton Oval,New Zealand,67,NaN
2,Abu Dhabi,"""ICC World Cricket League Championship",2016/01/29,952191,male,0,20,DT Jukes,NaN,Rabiul Hoque,...,Netherlands,field,United Arab Emirates,NaN,CK Nandan,Sarika Prasad,Sheikh Zayed Stadium,Netherlands,6,NaN
3,Coffs Harbour,NaN,2016/11/29,1043961,female,0,5,PL Marshall,EA Perry,DJ Shepard,...,South Africa,field,South Africa,NaN,PJ Gillespie,JD Ward,International Sports Stadium,Australia,43,NaN
4,,NaN,2016/08/31,995463,male,0,4,J Srinath,JW Hastings,REJ Martinesz,...,Australia,bat,Sri Lanka,Aleem Dar,MA Gough,RSA Palliyaguruge,Rangiri Dambulla International Stadium,Australia,NaN,6
5,Mirpur,NaN,2016/09/25,1051297,male,0,1,RB Richardson,Shakib Al Hasan,Tanvir Ahmed,...,Afghanistan,bat,Bangladesh,Anisur Rahman,C Shamshuddin,Sharfuddoula,Shere Bangla National Stadium,Bangladesh,7,NaN

In [149]:
odi_info.to_csv('./odi_info.csv',index=False)
ttwenty_info.to_csv('./ttwenty_info.csv',index=False)
odi_scorecard.to_csv('./odi_scorecard.csv',index=False)
ttwenty_scorecard.to_csv('./ttwenty_scorecard.csv',index=False)